[workspace]
resolver = "2"
members = [
    "wire-pacer",
    "wire-store",
    "wire-simd",
    "wire-core",
    "wire-tap",
    "wire-sim",
    "wire-echo",
    "wire-xdp",
    "wire-uring"
]

[workspace.dependencies]
libc = "0.2"
bitflags = "2.6"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
bytes = "1.7"
smallvec = "1.13"
thiserror = "1.0"
anyhow = "1.0"
io-uring = "0.6"
rustls = { version = "0.23", default-features = false, features = ["ring", "std"] }
ring = "0.17"
